### ISSUE TITLE
Can't use `httpgd` to render image.

### ISSUE THREAD

**Issue by lkyhfx** [scicloj/clojuress#89] opened 2023-12-30 08:14 UTC
I have attempted to use `httpgd` like this:
```
(require-r '[httpgd :refer [hgd hgd_browse]])
(hgd)
(->> rand
     (repeatedly 30)
     (reductions +)
     (plot :xlab "t" :ylab "y" :type "l"))
```
The image is rendered in the right sidebar successfully, but neither can you click the image to view or download. 
![image](https://github.com/scicloj/clojisr/assets/30225731/41107090-fb88-4134-8abe-f3a929d350fa)

It seams that httpgd server is closed.

**Comment by genmeblog** [comment] 2023-12-30 10:52
Confirmed.

When I called `grDevices/dev-list` the device (`httpgd`) is still active. `dev-off` hangs everything...

I need some time to investigate the issue.

**Comment by genmeblog** [comment] 2024-01-02 10:13
The problem is in the `httpgd` not in `clojisr` itself. I created an issue there: https://github.com/nx10/httpgd/issues/144

**Comment by genmeblog** [comment] 2024-04-14 18:30
Closing since it's not related to `clojisr`

**Closed as completed by genmeblog** 2024-04-14 18:30 UTC
